// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TicTacToeSDK.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Structure representing a given Tic Tac Toe board's state.
    /// </summary>
    public partial class Board
    {
        /// <summary>
        /// Initializes a new instance of the Board class.
        /// </summary>
        public Board() { }

        /// <summary>
        /// Initializes a new instance of the Board class.
        /// </summary>
        public Board(IList<string> gameBoard = default(IList<string>))
        {
            GameBoard = gameBoard;
        }

        /// <summary>
        /// A list of 9 position symbols ("X"|"O"|"?"), corresponding to the
        /// current state of a Tic Tac Toe board.
        /// Indices in this list correspond to a game board left-to-right,
        /// then top-to-bottom:
        /// 0 1 2
        /// 3 4 5
        /// 6 7 8
        /// </summary>
        [JsonProperty(PropertyName = "gameBoard")]
        public IList<string> GameBoard { get; set; }

    }
}
