// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TicTacToeSDK
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for TicTacToeSDKClient.
    /// </summary>
    public static partial class TicTacToeSDKClientExtensions
    {
            /// <summary>
            /// Plays a turn of Tic Tac Toe given the current board state.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startBoard'>
            /// The current state of the board.
            /// </param>
            public static object ExecuteMove(this ITicTacToeSDKClient operations, Board startBoard = default(Board))
            {
                return Task.Factory.StartNew(s => ((ITicTacToeSDKClient)s).ExecuteMoveAsync(startBoard), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Plays a turn of Tic Tac Toe given the current board state.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startBoard'>
            /// The current state of the board.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ExecuteMoveAsync(this ITicTacToeSDKClient operations, Board startBoard = default(Board), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ExecuteMoveWithHttpMessagesAsync(startBoard, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
